const g = [
   'Ganove',
   'Gebälk',
   'gediegen',
   'Gehabe',
   'geheftet',
   'Geländer',
   'gelinde',
   'Gemurmel',
   'Geplänkel',
   'gerinnen',
   'Gerippe',
   'gerissen',
   'gesalzen',
   'geschliffen',
   'geschniegelt',
   'Gestänge',
   'Gestell',
   'Getümmel',
   'Geturtel',
   'Gewebe',
   'Gewühl',
   'Gewummer',
   'Gier',
   'giggeln',
   'glotzen',
   'gluckern',
   'Gör',
   'Gosse',
   'grapschen',
   'Grünschnabel',
   'grunzen',
   'gurren',
   'Gurt',       
   'gut in Schuss',       
 ];

export default g;