const k = [
   'kahl',
   'kämmen',
   'karren',
   'Kaschemme',
   'kaschieren',
   'Kassiber',
   'katzbuckeln',
   'kauern',
   'kauzig',
   'keinen Reim machen können',
   'kichern',
   'Kieker (auf dem Kieker haben)',
   'Kiesweg',   
   'Kittel',   
   'klackern',
   'Kladde',
   'klamm',
   'Klammer',
   'klammern',
   'klappern',
   'Klapsmühle',
   'klatschen',
   'klauben',
   'Klaue',
   'Klemme',
   'klemmen',
   'Klette',
   'klimpern',
   'klirren',
   'klitzeklein',
   'Kloß',
   'Klüngel',
   'knarren',
   'kneten',
   'Knirps',
   'knebeln', 
   'knallen', 
   'kneten', 
   'Knöchel',  
   'Knochen hinhalten', 
   'knirschen',  
   'knistern', 
   'Knüppel',
   'knurren',
   'Köder',
   'Kontor',
   'köpfen',
   'Korb (einen Korb bekommen)',
   'Kordel',
   'Kot',
   'koten',
   'krabbeln',  
   'krachen', 
   'Krähe, krähen',  
   'krakelig/kraklig',
   'Kram (jmdm. in den Kram passen)',
   'kramen',
   'Kratzbürstigkeit',
   'kraulen',
   'Krempe',
   'Krempel',
   'Kribbeln',
   'kritzeln' ,
   'krümmen (sich)',
   'kullern',
   'Kuppel',
   'kurbeln',
   'kuscheln (sich)',
   'kuschen',
];

export default k;   