const p = [
   'Pappe',
   'petzen',
   'Pfanne (in die Pfanne hauen)',
   'Pfau'  ,
   'pfeffern',
   'Pfeiler',
   'pferchen',
   'pfiffig',
   'pfuschen (ins Handwerk pfuschen)',
   'pieksen, piksen',
   'Pinkel' ,
   'pinkeln' ,
   'pinseln' ,
   'platschen',
   'Platzhirsch',
   'ploppen' ,
   'poltern' ,
   'postieren',
   'präparieren' ,
   'Prise' ,
   'Protz' ,
   'Pulle',
   'Pute',
  ];

export default p;      