const r = [
   'Rabauke',
   'rabiat' ,
   'Radaubruder' ,
   'rammen'  ,
   'ramponiert' ,
   'Ratsch'  ,
   'rattern' ,
   'Räuberpistole' ,
   'Raunen' ,
   'Raureif' , 
   'reinsemmeln'  ,
   'reißen (sich um etwas)' ,
   'reißerisch' ,
   'renitent' ,
   'requirieren' ,
   'reüssieren',
   'Riegel'  ,
   'Rindvieh' ,
   'Rinnsal' ,
   'Ritze'  ,
   'robben' ,
   'röcheln',
   'roden' ,
   'rosten' ,
   'rumpeln',
   'rumsen',
   ];

export default r;      
